# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "/Users/fanjiang/go", "/home/vagrant/go"
  config.vm.provision "shell", path: "setup.sh"
end
